name: Run tests
on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "dev"]

jobs:
  release:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Run compilation test
        run: npm run build

      - name: Run test script
        run: npm test
